[build]
  publish = "dist"
  command = "npm run netlify:build"

[[redirects]]
  from = "/api/*"
  to = "/index.php"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
